version: "3"
services:
  restapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD/app:/usr/src/route/app
    ports:
      - 8080:8080
    environment:
      - APP_CONFIG_FILE=local
      - TZ=Asia/Tokyo
      - LC_CTYPE=C.UTF-8
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend:/usr/src/app/frontend
    ports:
      - 3000:3000
    tty: true